id = "fountain"
name = "Fountain"
description = "Fountain screenplay language support"
version = "0.1.0"
schema_version = 1
authors = ["Fountain LSP Team"]
repository = ""

languages = ["languages/fountain", "languages/fountain_inline"]

[grammars.fountain]
repository = "https://github.com/ArmingLou/fountain-tree-sitter"
rev = "17d2b4768f7e9520791425a041fb9234c8b60cea"

[grammars.fountain_inline]
repository = "https://github.com/ArmingLou/fountain-tree-sitter-inline"
rev = "9f710bffcace45975c1c05d855900f52a01e9683"

[language_servers.fountain-lsp]
name = "Fountain LSP"
language = "Fountain"
language_server_command = ["fountain-lsp"]
