id = "fountain"
name = "Fountain"
description = "Fountain screenplay language support"
version = "0.1.0"
schema_version = 1
authors = ["Fountain LSP Team"]
repository = ""

languages = ["languages/fountain", "languages/fountain_inline"]

[grammars.fountain]
repository = "https://github.com/ArmingLou/fountain-tree-sitter"
rev = "fda536274e1ca702bd9513d2231cbb974c458e25"

[grammars.fountain_inline]
repository = "https://github.com/ArmingLou/fountain-tree-sitter-inline"
rev = "b599c75cd564c303fd833a36d3cda0825e37b9d6"

[language_servers.fountain-lsp]
name = "Fountain LSP"
language = "Fountain"
language_server_command = ["fountain-lsp"]
